services:    
    pgadmin:
        image: dpage/pgadmin4:9.9
        #ports:
        #    - "8088:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_LISTEN_PORT=80
        networks:
            - mired
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.universidad.localhost`)"
            - "traefik.http.routers.pgadmin.tls=true"
            - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
            - "traefik.docker.network=mired"
networks:
    mired:
        external: true
